/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategorySection: typeof import('./src/components/sections/CategorySection/CategorySection.vue')['default']
    CollectionSection: typeof import('./src/components/sections/CollectionSection/CollectionSection.vue')['default']
    FeaturedSection: typeof import('./src/components/sections/FeaturedSection/FeaturedSection.vue')['default']
    FooterBase: typeof import('./src/components/FooterBase.vue')['default']
    MobileMenu: typeof import('./src/components/core/MobileMenu/MobileMenu.vue')['default']
    Navigation: typeof import('./src/components/core/Navigation/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryNavigation: typeof import('./src/components/core/SecondaryNavigation/SecondaryNavigation.vue')['default']
  }
}
